/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.4
 * Generated at: 2017-07-06 03:08:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class banner_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!-- topbar starts -->\n");
      out.write("\n");
      out.write("<div class=\"header navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("\n");
      out.write("\t<!-- BEGIN TOP NAVIGATION BAR -->\n");
      out.write("\n");
      out.write("\t<div class=\"navbar-inner\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- BEGIN LOGO -->\n");
      out.write("\n");
      out.write("\t\t\t<a  class=\"brand\" style=\"text-align:center;font-size: 15px;color: white;width:170px;\" href=\"index.html\"> \n");
      out.write("\t\t\t\t纵横数据中心\n");
      out.write("\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t<!-- END LOGO -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- BEGIN RESPONSIVE MENU TOGGLER -->\n");
      out.write("\n");
      out.write("\t\t\t<a href=\"javascript:;\" class=\"btn-navbar collapsed\"\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\".nav-collapse\"> <img\n");
      out.write("\t\t\t\tsrc=\"css/images/menu-toggler.png\" alt=\"\" />\n");
      out.write("\n");
      out.write("\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t<!-- END RESPONSIVE MENU TOGGLER -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- BEGIN TOP NAVIGATION MENU -->\n");
      out.write("\n");
      out.write("\t\t\t<ul class=\"nav pull-right\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- BEGIN USER LOGIN DROPDOWN -->\n");
      out.write("\n");
      out.write("\t\t\t\t<li class=\"dropdown user\"><a href=\"#\" class=\"dropdown-toggle\"\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\"> <img alt=\"\"\n");
      out.write("\t\t\t\t\t\tsrc=\"img/avatar1_small.jpg\" /> <span id=\"userNameId\" class=\"username\">Bob\n");
      out.write("\t\t\t\t\t\t\tNilson</span> <i class=\"icon-angle-down\"></i>\n");
      out.write("\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a id=\"myProfileId\" href=\"javascript:void(0)\"><i class=\"icon-user\"></i>My Profile</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a id=\"loginOutId\" href=\"javascript:void(0)\"><i class=\"icon-key\"></i> Log Out</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- END USER LOGIN DROPDOWN -->\n");
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t<!-- END TOP NAVIGATION MENU -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- END TOP NAVIGATION BAR -->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"js/customer/banner.js\"></script>\n");
      out.write("<!-- topbar ends -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
