/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.4
 * Generated at: 2017-07-04 02:53:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class leftMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!-- topbar starts -->\n");
      out.write("<div id=\"leftMenuId\" class=\"page-sidebar nav-collapse collapse\">\n");
      out.write("\n");
      out.write("\t<!-- BEGIN SIDEBAR MENU -->\n");
      out.write("\n");
      out.write("\t<ul class=\"page-sidebar-menu\">\n");
      out.write("\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t<!-- BEGIN SIDEBAR TOGGLER BUTTON -->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"sidebar-toggler hidden-phone\"></div> <!-- BEGIN SIDEBAR TOGGLER BUTTON -->\n");
      out.write("\n");
      out.write("\t\t</li>\n");
      out.write("\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->\n");
      out.write("\n");
      out.write("\t\t\t<form class=\"sidebar-search\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"input-box\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" class=\"remove\"></a> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Search...\" /> <input type=\"button\" class=\"submit\"\n");
      out.write("\t\t\t\t\t\tvalue=\" \" />\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</form> <!-- END RESPONSIVE QUICK SEARCH FORM -->\n");
      out.write("\n");
      out.write("\t\t</li>\n");
      out.write("\t\t<li class=\"start active\">\n");
      out.write("\t\t   <a href=\"pages/home.jsp\">\n");
      out.write("\t\t     <i class=\"icon-home\"></i> \n");
      out.write("\t\t     <span class=\"title\">Dashboard</span> \n");
      out.write("\t\t     <span class=\"selected\"></span>\n");
      out.write("\t\t   </a>\n");
      out.write("\t\t</li>\n");
      out.write("\n");
      out.write("\t\t<li class=\"\">\n");
      out.write("\t\t   <a href=\"javascript:;\"> \n");
      out.write("\t\t\t   <i class=\"icon-cogs\"></i>\n");
      out.write("\t\t\t   <span class=\"title\">Layouts</span>\n");
      out.write("\t\t\t   <span class=\"arrow \"></span>\n");
      out.write("\t\t   </a>\n");
      out.write("\t\t   <ul class=\"sub-menu\">\n");
      out.write("\t\t     <li class=\"\"><a href=\"layout_horizontal_sidebar_menu.html\">Horzontal & Sidebar Menu</a></li>\n");
      out.write("\t         <li><a href=\"layout_horizontal_menu1.html\"> Horzontal Menu1</a></li>\n");
      out.write("\t\t   </ul>\n");
      out.write("\t\t</li>\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t<a class=\"active\" href=\"javascript:;\">\n");
      out.write("\t\t\t\t<i class=\"icon-sitemap\"></i>\n");
      out.write("\t\t\t\t<span class=\"title\">3 Level Menu</span>\n");
      out.write("\t\t\t\t<span class=\"arrow \"></span>\n");
      out.write("\t\t\t</a>\n");
      out.write("\t\t\t<ul class=\"sub-menu\">\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t    <a href=\"javascript:;\"> Item 1 <span class=\"arrow\"></span></a>\n");
      out.write("\t\t\t\t\t<ul class=\"sub-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Sample Link 1</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Sample Link 2</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Sample Link 3</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t   </li>\n");
      out.write("\t\t\t   <li>\n");
      out.write("\t\t\t   \t\t<a href=\"javascript:;\"> Item 1 <span class=\"arrow\"></span></a>\n");
      out.write("\t\t\t\t\t<ul class=\"sub-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Sample Link 1</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Sample Link 1</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Sample Link 1</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t   </li>\n");
      out.write("\t\t       <li><a href=\"#\"> Item 3 </a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</li>\n");
      out.write("</ul>\n");
      out.write("\n");
      out.write("\t<!-- END SIDEBAR MENU -->\n");
      out.write("<script type=\"text/javascript\" src=\"js/customer/leftmenu.js\"></script>\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
