/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.4
 * Generated at: 2017-07-06 01:11:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\" />\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "dependency/comcss.jsp", out, true);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "dependency/comjs.jsp", out, true);
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/customer/login-soft.css\" />\n");
      out.write("<title>纵横数据中心</title>\n");
      out.write("</head>\n");
      out.write("<body class=\"login\">\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "dependency/notyDependency.jsp", out, true);
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"logo\"></div>\n");
      out.write("\n");
      out.write("\t<div class=\"content row-fluid\">\n");
      out.write("\t\t<form class=\"form-vertical login-form\" action=\"javascript:;\"\n");
      out.write("\t\t\tmethod=\"post\">\n");
      out.write("\t\t\t<h3 class=\"form-title\">用户登陆中心</h3>\n");
      out.write("\t\t\t<div id=\"errorMsgId\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">用户账号</label>\n");
      out.write("\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t<div class=\"input-icon left\">\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-user\"></i> \n");
      out.write("\t\t\t\t\t\t<input id=\"username\" class=\"m-wrap placeholder-no-fix\" type=\"text\" placeholder=\"用户账号\" name=\"username\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">用户密码</label>\n");
      out.write("\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t<div class=\"input-icon left\">\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-lock\"></i> \n");
      out.write("\t\t\t\t\t\t<input id=\"password\" class=\"m-wrap placeholder-no-fix\" type=\"password\" placeholder=\"用户密码\" name=\"password\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-actions\" style=\"margin-left: -10px\">\n");
      out.write("\t\t\t\t<label class=\"checkbox\"> \n");
      out.write("\t\t\t\t\t<input id=\"remember\"style=\"margin-top: 1px;\"type=\"checkbox\"> <span>记住</span>\n");
      out.write("\t\t\t\t</label> \n");
      out.write("\t\t\t\t<a id=\"signBtn\" href=\"javascript:void(0)\" class=\"btn blue pull-right\">登陆 <i class=\"icon-signin\"></i></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"forget-password\">\n");
      out.write("\t\t\t\t<h4>忘记密码 ?</h4>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t不用担心, 点击 <a href=\"javascript:;\" class=\"\" id=\"forget-password\">这里</a>重置您的密码.\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"create-account\">\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t尚未拥有账号 ?&nbsp; <a href=\"pages/register.jsp\" id=\"register-btn\" class=\"\">注册新用户</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div style=\"bottom: 0px;position: absolute;color: white;\">2017 &copy; ZONGHENG BY DS.</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\t<script src=\"js/customer/login.js\"></script>\n");
      out.write("\t<div class=\"footer\" style=\"width: 100%;text-align: center;\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"footer-tools\">\n");
      out.write("\t\t\t<span class=\"go-top\"> <i class=\"icon-angle-up\"></i></span>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
